# Generated by Django 5.2.7 on 2025-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
