# Generated by Django 5.2.7 on 2025-10-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_questionnaire_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='additional_notes',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='main_complaint',
            field=models.CharField(blank=True, choices=[('RUECKEN', 'Rückenschmerzen'), ('KOPF', 'Kopfschmerzen'), ('GELENK', 'Gelenkschmerzen'), ('SONSTIGES', 'Sonstiges')], max_length=20, null=True),
        ),
    ]
