# Generated by Django 5.2.7 on 2025-11-10 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_disease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read_by_patient',
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_practitioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_practitioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='polls.patient'),
        ),
        migrations.AlterField(
            model_name='message',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='polls.practitioner'),
        ),
    ]
