# Generated by Django 5.2.7 on 2025-10-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_questionnaire_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question3',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question4',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pain_duration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wie lange haben Sie die Beschwerden schon?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pain_frequency',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wie oft treten die Beschwerden auf?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pain_intensity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wie stark sind die Beschwerden?'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='previous_treatment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wurden Sie wegen dieser Beschwerden schon behandelt?'),
        ),
    ]
