"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ymlh*=xpx@+jf^l49kc+esn*9e+ai96gg6+9!@x#b+0klz=w6@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

secrets = {
    "AZURE_SQL_HOST": "misue01.database.windows.net",
    "AZURE_SQL_USER": "Ginga_Gramel", 
    "AZURE_SQL_PASSWORD": "Fefe11scw",
    "AZURE_SQL_DATABASE": "MIS_UE01",
    "AZURE_SQL_SERVERNAME": "misue01",
}
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# def inferDatabaseConfig():
#     # Wenn Azure-SQL-Settings vorhanden sind
#     if "AZURE_SQL_HOST" in secrets:
#         print("Connecting to Azure SQL Database...")
#         return {
#             "ENGINE": "mssql",
#             "NAME": secrets["AZURE_SQL_DATABASE"],
#             "USER": f"{secrets['AZURE_SQL_USERNAME']}@{secrets['AZURE_SQL_SERVERNAME']}",
#             "PASSWORD": secrets["AZURE_SQL_PASSWORD"],
#             "HOST": secrets["AZURE_SQL_HOST"],
#             "PORT": "",
#             "OPTIONS": {
#                 "driver": "ODBC Driver 18 for SQL Server",
#                 "encrypt": True,
#                 "trust_server_certificate": False,
#             },
#         }
 
#     # Wenn PostgreSQL-Umgebung aktiv ist
#     if "POSTGRES_HOST" in os.environ:
#         return {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": "misue01.database.windows.net",
#             "USER": os.environ["POSTGRES_USER"],
#             "PASSWORD": os.environ["POSTGRES_PASSWORD"],
#             "HOST": os.environ["POSTGRES_HOST"],
#             "PORT": os.environ["POSTGRES_PORT"],
#         }
 
#     # Standard-Fallback auf SQLite
#     return {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
 
 
 
# DATABASES = {
#     'default': inferDatabaseConfig()
# }
 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Add these at the top of your settings.py
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()

# Replace the DATABASES section of your settings.py with this
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}